### ISSUE TITLE
invalid command name ".!navigationtoolbar2tk.!button2"

### ISSUE THREAD

**Issue by sebaspm24** [DCMLab/pitchplots#48]
Hi, Im new with pitchplots and got a problem while testing the ploting function. Can you help with that?:

> Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

>import pitchplots.parser as ppp

>df_data_example = ppp.xml_to_csv(save_csv=True)

>import pitchplots.static as pps

>pps.tonnetz(df_data_example)

>Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    pps.tonnetz(df_data_example)
  File "C:\Program Files\Python38\lib\site-packages\pitchplots\static.py", line 458, in tonnetz
    ax = fig.add_subplot(111, aspect='equal')
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 1404, in add_subplot
    return self._add_axes_internal(key, ax)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 1409, in _add_axes_internal
    self.sca(ax)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 2070, in sca
    self._axobservers.process("_axes_change_event", self)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 229, in process
    self.exception_handler(exc)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 81, in _exception_printer
    raise exc
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 224, in process
    func(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 2167, in <lambda>
    self._axobservers.connect("_axes_change_event", lambda arg: func(arg))
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backend_bases.py", line 2712, in notify_axes_change
    self.toolbar.update()
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backend_bases.py", line 3276, in update
    self.set_history_buttons()
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backends\_backend_tk.py", line 667, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1648, in __setitem__
    self.configure({key: value})
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"

Thanks.

**Comment by fabianmoss** [comment]
Hi!

Could you please provide a bit more information: It looks like you wanted to create a Tonnetz plot, right? Which file was you input? Can you provide a minimal example? Are you using pitchplots in the terminal or a notebook?
Answers to these questions will help me to determine where the error occurs.

Also, please use the "Insert Code" button which makes it easier to read. Quotes have a different purpose.

**Comment by sebaspm24** [comment]
Hi,

I was just following the instructions in [README.md ](https://github.com/DCMLab/pitchplots/blob/master/README.md) . I'm not loading any file, so it should charge data_example.mxl (an it does, also generates the .csv file from that). The problem appears when I try to create the Tonnetz (with circle or line is the same error).

I'm using Python 3.8 on Windows10 (64bit) and the shell from Python-IDLE.

Sorry about inserting a quote. Here is the code again:

```
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import pitchplots.parser as ppp
>>> df_data_example = ppp.xml_to_csv(save_csv=True)
>>> import pitchplots.static as pps
>>> pps.tonnetz(df_data_example)
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    pps.tonnetz(df_data_example)
  File "C:\Program Files\Python38\lib\site-packages\pitchplots\static.py", line 458, in tonnetz
    ax = fig.add_subplot(111, aspect='equal')
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 1404, in add_subplot
    return self._add_axes_internal(key, ax)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 1409, in _add_axes_internal
    self.sca(ax)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 2070, in sca
    self._axobservers.process("_axes_change_event", self)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 229, in process
    self.exception_handler(exc)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 81, in _exception_printer
    raise exc
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 224, in process
    func(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 2167, in <lambda>
    self._axobservers.connect("_axes_change_event", lambda arg: func(arg))
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backend_bases.py", line 2712, in notify_axes_change
    self.toolbar.update()
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backend_bases.py", line 3276, in update
    self.set_history_buttons()
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backends\_backend_tk.py", line 667, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1648, in __setitem__
    self.configure({key: value})
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"
>>> 
```

**Comment by fabianmoss** [comment]
I cannot reproduce your error. Which matplotlib version do you have? You can check with

```
import matplotlib
matplotlib.__version__
```
I'm using version 3.2.2 and everything works fine. Maybe try updating yours.

**Comment by sebaspm24** [comment]
I was using 3.3.2. Now I have installed the 3.2.2 version and it looks better:

```
import pitchplots.parser as ppp
import pitchplots.static as pps
e=pps.tonnetz('C:/csv/data_example.csv')
e
<Figure size 700x400 with 2 Axes>
```
With `e.savefig` can I save the figure but it doesn't show it at the moment. Is there a trick to do that?

**Comment by fabianmoss** [comment]
The following should work for you:

```python
import pitchplots.parser as ppp
import pitchplots.static as pps
import matplotlib.pyplot as plt

df_data_example = ppp.xml_to_csv(save_csv=True)
fig = pps.tonnetz(df_data_example)
fig.show()
```

**Comment by sebaspm24** [comment]
Thank you for your help. Unfortunately I get a problem with that:

```
>>> import pitchplots.parser as ppp
>>> import pitchplots.static as pps
>>> import matplotlib.pyplot as plt
>>>df_data_example = ppp.xml_to_csv(save_csv=True)
>>> fig=pps.tonnetz(df_data_example)
>>> fig.show()
```
I get:
```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    fig.show()
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\figure.py", line 443, in show
    manager.show()
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\backends\_backend_tk.py", line 482, in show
    self.canvas._tkcanvas.bind("<Destroy>", destroy)
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1383, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1337, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
```

**Comment by fabianmoss** [comment]
It seems to have still something to do with your matplotlib installation which attempts loading tkinter. Maybe update this library, too and see whether that solves the problem.

**Comment by fabianmoss** [comment]
Please close the issue if it is resolved.

**Comment by sebaspm24** [comment]
Thanks for your help. 

I still have troubles with `show()` (it actually works with other graphs from Music21) but it's enough that I can save the image.
